# ==============================================================================
# 1. METADADOS DO PROJETO
# ==============================================================================
# Nome do aplicativo (deve ser em minúsculas, com underscores)
name: entregas_woocommerce

# Descrição do projeto
description: "A new Flutter project."

# Impede publicação acidental no pub.dev (ideal para apps privados)
publish_to: 'none' # Remova ou comente esta linha se for publicar

# Versão do app: major.minor.patch+build
# Ex: 1.0.0+1
# - "1.0.0" é a versão de release (CFBundleShortVersionString no iOS, versionName no Android)
# - "+1" é o número de build (CFBundleVersion no iOS, versionCode no Android)
version: 1.0.0+1

# ==============================================================================
# 2. AMBIENTE E SDK
# ==============================================================================
# Define a versão do SDK Dart compatível
# ^3.8.1 significa: 3.8.1 ou superior, mas menor que 4.0.0
environment:
  sdk: ^3.8.1

# ==============================================================================
# 3. DEPENDÊNCIAS (Pacotes necessários para o app funcionar)
# ==============================================================================
dependencies:
  # SDK do Flutter (obrigatório)
  flutter:
    sdk: flutter

  # Ícones do Cupertino (iOS-style)
  cupertino_icons: ^1.0.8

  # Conexão com Supabase (banco de dados)
  supabase_flutter: ^2.7.0

  # Gerenciamento de estado (Provider)
  provider: ^6.1.0

  # Formatação de datas, moedas, etc.
  intl: ^0.18.1

  # Geração de PDFs
  pdf: ^3.8.0

    # Url da logo do recibo
  http: ^1.1.0
  cached_network_image: ^3.3.0
  url_launcher: ^6.1.11

  # Acesso ao sistema de arquivos (para salvar PDFs)
  path_provider: ^2.1.1

# ==============================================================================
# 4. DEPENDÊNCIAS DE DESENVOLVIMENTO (apenas para testes e análise)
# ==============================================================================
dev_dependencies:
  # SDK para testes do Flutter
  flutter_test:
    sdk: flutter

  # Boas práticas de código (lints)
  flutter_lints: ^5.0.0

# ==============================================================================
# 5. CONFIGURAÇÃO DO FLUTTER (recursos visuais e assets)
# ==============================================================================
# Tudo abaixo é específico do Flutter
flutter:

  # Ativa o uso de ícones do Material Design
  uses-material-design: true

  # ==============================================================================
  # 5.1 ASSETS (arquivos incluídos no app)
  # ==============================================================================
  # Arquivos estáticos que serão embutidos no app
  assets:
    # Fontes customizadas
    - assets/fonts/Roboto-Regular.ttf
    - assets/fonts/Roboto-Italic.ttf

  # ==============================================================================
  # 5.2 FONTES CUSTOMIZADAS (opcional - se quiser definir famílias)
  # ==============================================================================
  # Se você quiser usar o nome 'Roboto' no TextStyle, descomente abaixo
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Italic.ttf
  #         style: italic

# ==============================================================================
# 6. NOTAS
# ==============================================================================
# - Para mais informações sobre o formato do pubspec.yaml:
#   https://dart.dev/tools/pub/pubspec
#
# - Para versionamento no Android:
#   https://developer.android.com/studio/publish/versioning
#
# - Para versionamento no iOS:
#   https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html